---

repository: aereal/otelpubsub/${COMPONENT}
coverage:
  if: true
codeToTestRatio:
  code:
    - '**/*.go'
    - '!**/*_test.go'
  test:
    - '**/*_test.go'
testExecutionTime:
  if: true
diff:
  datastores:
    - artifact://${GITHUB_REPOSITORY}/${COMPONENT}
report:
  datastores:
    - artifact://${GITHUB_REPOSITORY}/${COMPONENT}
comment:
  if: is_pull_request
summary:
  if: is_pull_request
